services:
  pgvector:
    image: pgvector/pgvector:pg17
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD
    ports:
      - '5432:5432'

volumes:
  pgvector_data:
